version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: ura-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ura_root_2026
      MYSQL_DATABASE: ura_db
      MYSQL_USER: ura_user
      MYSQL_PASSWORD: ura_pass_2026
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: ura-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data: